import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Testing",
    description: "Generated by create next app",
    keywords: "cia",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <nav>
                        <Link href="/">Home</Link>
                        <Link href="/joma">Joma</Link>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    );
}
